### ISSUE TITLE
bug: openlab file push - "error": "authentication check failed: (0)" 

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-cli#18] opened 2022-03-04 08:29 UTC
This is probably related to #16 

rindtorff@niklas labdao % openlab file push assets/logo.png 
{
  "error": "authentication check failed: (0)"
}

**Comment by NiklasTR** [comment] 2022-04-11 18:14
@blahah - is this bug fixed? I was just playing with Aakaash's branch. I think we should try to prioritize it - will make the process of pinning job objects and token objects less painful.

**Comment by blahah** [comment] 2022-04-12 13:06
@NiklasTR this isn't a bug. Anyone is free to fork the repo and make a PR. Permission to directly modify the repo is strictly limited for security.

The solution is to fork the repo and make a PR if one wants to propose a contribution.

**Comment by blahah** [comment] 2022-07-04 21:17
Duplicate of #16, fixed in 3ce8a84158446d5fd0c61aba8e8a7bbe5cc23cdf

**Closed as completed by blahah** 2022-07-04 21:17 UTC
Labels: bug
